[build-system]
requires = ["setuptools>=40.8.0", "wheel", "Cython", "numpy>=1.16.0"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.cibuildwheel]
before-build = "python -m pip install cython numpy"
skip = "pp*"
