# Python CircleCI 2.0 configuration file
version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: cimg/python:3.12.8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - run: echo 'export PYTHONPATH=$HOME/repo' >> $BASH_ENV

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install codecov setuptools

      - run:
          name: install openjdk
          command: |
            sudo apt update
            sudo apt install default-jdk

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py build_ext --inplace
            pytest --cov=./sklearn_pmml_model tests/

      - run:
          name: coverage report
          command: |
            . venv/bin/activate
            python -m codecov

      - store_artifacts:
          path: test-reports
          destination: test-reports
